name: CI

# Use bash by default on all platforms.
defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - README.rst

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
          - os: 'macos-latest'
      fail-fast: false

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        gcc -Wall -W -O2 testsigpipe.c -o testsigpipe

    - name: Run
      run: |
        ./testsigpipe
