name: CI

# Use bash by default on all platforms.
defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - README.rst

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          #- os: 'ubuntu-latest'
          #- os: 'macos-11'
          #- os: 'macos-latest'
          #- vm: 'dragonflybsd'
          #- vm: 'freebsd'
          #- vm: 'netbsd'
          #- vm: 'openbsd'
          - vm: 'solaris'
      fail-fast: false

    runs-on: ${{ matrix.os || 'macos-12' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run in DragonflyBSD VM
      uses: vmactions/dragonflybsd-vm@v0
      if: matrix.vm == 'dragonflybsd'
      with:
        usesh: true
        copyback: false
        run: |
          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
          ./testsigpipe

    - name: Run in FreeBSD VM
      uses: vmactions/freebsd-vm@v0
      if: matrix.vm == 'freebsd'
      with:
        usesh: true
        copyback: false
        run: |
          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
          ./testsigpipe

    - name: Run in NetBSD VM
      uses: vmactions/netbsd-vm@v0
      if: matrix.vm == 'netbsd'
      with:
        usesh: true
        copyback: false
        run: |
          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
          ./testsigpipe

    - name: Run in OpenBSD VM
      uses: vmactions/openbsd-vm@v0
      if: matrix.vm == 'openbsd'
      with:
        usesh: true
        copyback: false
        run: |
          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
          ./testsigpipe

    - name: Run in Solaris VM
      uses: vmactions/solaris-vm@v0
      if: matrix.vm == 'solaris'
      with:
        usesh: true
        copyback: false
        prepare: |
          pkgutil -y -i gcc5core
        run: |
          gcc -Wall -W -O2 testsigpipe.c -o testsigpipe
          ./testsigpipe

    - name: Build
      if: matrix.vm == ''
      run: |
        gcc -Wall -W -O2 testsigpipe.c -o testsigpipe

    - name: Run
      if: matrix.vm == ''
      run: |
        ./testsigpipe
