name: CI

# Use bash by default on all platforms.
defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - README.rst

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          #- os: 'ubuntu-latest'
          #- os: 'macos-latest'
          #- os: 'macos-26-intel'
          #- os: 'macos-15-intel'
          #- os: 'macos-26'
          #- os: 'macos-15'
          #- os: 'macos-14'
          #- vm: 'dragonflybsd'
          #- vm: 'freebsd'
          #- vm: 'netbsd'
          #- vm: 'openbsd'
          #- vm: 'solaris'
          - os: 'windows-latest'
          - os: 'windows-2022'
          - os: 'windows-11-arm'
      fail-fast: false

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6

#    - name: Run in DragonflyBSD VM
#      uses: vmactions/dragonflybsd-vm@v1
#      if: matrix.vm == 'dragonflybsd'
#      with:
#        usesh: true
#        copyback: false
#        run: |
#          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
#          ./testsigpipe
#
#    - name: Run in FreeBSD VM
#      uses: vmactions/freebsd-vm@v1
#      if: matrix.vm == 'freebsd'
#      with:
#        usesh: true
#        copyback: false
#        run: |
#          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
#          ./testsigpipe
#
#    - name: Run in NetBSD VM
#      uses: vmactions/netbsd-vm@v1
#      if: matrix.vm == 'netbsd'
#      with:
#        usesh: true
#        copyback: false
#        run: |
#          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
#          ./testsigpipe
#
#    - name: Run in OpenBSD VM
#      uses: vmactions/openbsd-vm@v1
#      if: matrix.vm == 'openbsd'
#      with:
#        usesh: true
#        copyback: false
#        run: |
#          cc -Wall -W -O2 testsigpipe.c -o testsigpipe
#          ./testsigpipe
#
#    - name: Run in Solaris VM
#      uses: vmactions/solaris-vm@v1
#      if: matrix.vm == 'solaris'
#      with:
#        usesh: true
#        copyback: false
#        prepare: |
#          pkgutil -y -i gcc5core
#        run: |
#          gcc -Wall -W -O2 testsigpipe.c -o testsigpipe
#          ./testsigpipe
#
#    - name: Build
#      if: matrix.vm == '' && !contains(matrix.os, 'windows')
#      run: |
#        gcc -Wall -W -O2 testsigpipe.c -o testsigpipe
#
#    - name: Run
#      if: matrix.vm == '' && !contains(matrix.os, 'windows')
#      run: |
#        ./testsigpipe

    - name: Test FILE_SHARE_DELETE
      if: contains(matrix.os, 'windows')
      run: |
        gcc -Wall -W -O2 file-share-delete.c -o file-share-delete
        ./file-share-delete

    - name: Test atomic rename
      if: contains(matrix.os, 'windows')
      run: |
        git checkout .
        gcc -Wall -W -O2 atomic-rename.c -o atomic-rename
        ./atomic-rename

#    - name: Check GL
#      if: matrix.vm == ''
#      run: |
#        for h in GL OpenGL ; do echo "#include <$h/gl.h>"|gcc -xc -Wall -W -c - || echo FAILED ; done
